<a href="https://colab.research.google.com/github/hamranmohamed05-blip/data--science--project/blob/main/python_123.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# variables and data types

In [ ]:
number1="ham"

In [ ]:
number1

'ham'

In [ ]:
type(number1)

str

##operators

In [ ]:
a=10
b=20
a+b

30

In [ ]:
a>b

False

In [ ]:
a<b

True

#CONDITIONAL STATEMENT

In [ ]:
age = 18
if age >=18:
  print ("you are allowed to access the app")
else :
      print ("you are not allowed to access the app")

you are allowed to access the app

In [ ]:
nationality = "ind"
age =18
if age >=18 and nationality =="ind":


  print ("you are allowed to access the app")
else :
      print ("you are not allowed to access the app")

you are allowed to access the app

#LOOP

### while loop

In [ ]:
count =1

while count<= 5:
  print ("ham",count)
  count = count + 1

ham 1
ham 2
ham 3
ham 4
ham 5

## for loop

In [ ]:
for number in range (5) :#range (5) - 0,2,3,4,1
  print("ham",number)

ham 0
ham 1
ham 2
ham 3
ham 4

##function

In [ ]:

def multiple(a,b):
  return a*b

In [ ]:
multiple(10,20)

200

#pandas library

In [ ]:
import pandas as pd
import numpy as np

In [11]:
import pandas as pd

df =pd.read_csv('/content/1.02. Multiple linear regression.csv')
df

     SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [14]:
df.columns

Index(['SAT', 'GPA', 'Rand 1,2,3'], dtype='object')

In [15]:
df['GPA']

0     2.40
1     2.52
2     2.54
3     2.74
4     2.83
      ...
79    3.71
80    3.71
81    3.73
82    3.76
83    3.81
Name: GPA, Length: 84, dtype: float64